### PR TITLE
Adds missing Kosovo and South Sudan IOC to ISO codes

### PR DESCRIPTION
**Pull request by egaban**
Kosovo and South Sudan didn't have IOC to ISO entries

### CODE REVIEW

**Comment by Mogost** [comment]
I guess this will not be accepted 
See  https://github.com/SmileyChris/django-countries/issues/5

Also there are many other issues about Kosovo in this repo. Try to search

**Comment by egaban** [comment]
Sorry, that makes sense. But according to Wikipedia, South Sudan appears to have an ISO code. Would it make sense to add it in the list?

**Comment by Mogost** [comment]
Wiki is not a source of true for this project. 
https://github.com/SmileyChris/django-countries/blob/2547f4de0dba9c858e1875e55f7a9032cb6315f2/django_countries/data.py#L2-L16

Could you check according to this doc?

South Sudan seems to have a code, unlike Kosovo.

**Comment by egaban** [comment]
Yeah, just checked that iso.org link, and it does have South Sudan code.

**Pull request closed without merging**
