### PR TITLE
Updates CountryField for django 3.2 compatibility.

### PR DESCRIPTION
**Pull request by robcharlwood**
Django 3.2 updates the underlying ``CharField`` to include new logic for ``db_collation``.  This change set fixes the ``CountryField`` so that it is compatible with the new constructor format.

### CODE REVIEW

**Comment by SmileyChris** [comment]
We're calling `super().__init__` in CountryField's `__init__` -- isn't that enough since you're just duplicating the behaviour of the underlying `CharField`?

**Comment by robcharlwood** [comment]
> We're calling `super().__init__` in CountryField's `__init__` -- isn't that enough since you're just duplicating the behaviour of the underlying `CharField`?
> 
> If I'm overlooking something, can you provide a simple test to show what's currently broken?

Hi Chris, 

Thanks for getting back to me. Apologies, I don't believe I explained myself very well - The issue is within ``deconstruct`` Deconstruct in the base ``CharField`` uses ``self.db_collation`` which prior to my PR was not being set in ``CountryField``. So this in turn was causing the below exception to be raised. :) 

```bash
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <django_countries.fields.CountryField: country>

    def deconstruct(self):
        name, path, args, kwargs = super().deconstruct()
>       if self.db_collation:
E       AttributeError: 'CountryField' object has no attribute 'db_collation'

.venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1089: AttributeError
```

**Comment by robcharlwood** [comment]
Relevant lines in django are:

https://github.com/django/django/blob/main/django/db/models/fields/__init__.py#L1004-L1006

and 

https://github.com/django/django/blob/main/django/db/models/fields/__init__.py#L1087-L1091

**Comment by robcharlwood** [comment]
Gentle little bump on this please. 🤗

**Comment by nijel** [comment]
7.1 IMHO already contains fix for this...

**Comment by robcharlwood** [comment]
Indeed, 7.1 does seem to fix this. My ``poetry`` file needed bumping so as to get the latest major version (I was running 5.5)

**Pull request closed without merging**
