### PR TITLE
Adds Kosovo

### PR DESCRIPTION
**Pull request by richardARPANET**

### CODE REVIEW

**Comment by richardARPANET** [comment]
@SmileyChris Code review please

**Comment by Mogost** [comment]
https://github.com/SmileyChris/django-countries/blob/54c2fd3f9dd92e0868c5d7bf551479b9a90e4ae0/django_countries/data.py#L3-L15
The code is not present in the official standard.

**Comment by richardARPANET** [comment]
That's nice @Mogost, however:

https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

> The code XK is being used by the European Commission,[24] the IMF, and SWIFT,[25] CLDR and other organizations as a temporary country code for Kosovo.[26]

Plus it's on many of these country code websites https://allcountrycode.com/kosovo

Plus I need this in this lib as the TikTok API is using XK.

So, fuck the standard.

**Comment by barm** [comment]
Couple thoughts on this:

- Kosovo is included in a frontend lib we're using and this caused some skew between frontend and backend validation, which is how I arrived here. 
- We at http://github.com/cadre are going to add Kosovo through the `COUNTRIES_OVERRIDE` in order to provide support. This is a pretty nice way to allow customization, thanks for providing it. 
- We also have a team member from Kosovo, which has highlighted to me the consequences of small decisions like this. For example, he almost missed an international flight because, during booking, he was not able to select Kosovo in a citizenship dropdown. Upon checkin at the airport, he was held up because his passport did not match his selected citizenship.
- It seems like one of the potential downsides of adding Kosovo (and potentially other disputed territories) would be mismatch between libraries, but the consequences of not providing these types of options are real.
- One way to resolve this issue would be to provide a default expanded set with Kosovo but allow developers to optionally limit to a strict iso3166-1 set. You could decide to do the opposite, but I'd argue that having the more full set as the default would cause minimal harm and provide benefit to people from disputed territories. Either feels better than having developers explicitly provide overrides for disputed territories which they have to research themselves to even know about.

**Comment by SmileyChris** [comment]
I'm going to say we stick with the status quo for countries provided by default. It probably makes sense to have disputed country names somewhere within the project though so they can be consistently added by third parties through the use of COUNTRIES_OVERRIDE while retaining the ability to have them translatable.

**Pull request closed without merging**
