### PR TITLE
Run tests against Python 3.7.

### PR DESCRIPTION
**Pull request by schinckel**
Not sure yet if I have the travis/tox stuff set up right.

### CODE REVIEW

**Comment by schinckel** [comment]
Okay. No Python3.7 on travis?

**Comment by SmileyChris** [comment]
Yeah, great right? I would've done it along with the other tests I added.

Still possible, just inconvenient.

**Comment by akshaybabloo** [comment]
Travis doesn't, by default have Python 3.7 in its default build. You'll have you build a matrix for that.

```yaml
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
```

**Comment by SmileyChris** [comment]
Fixed in 1504e6a

**Pull request closed without merging**
