### PR TITLE
Fix some accents in French localization

### PR DESCRIPTION
**Pull request by laowantong**

### CODE REVIEW

**Comment by SmileyChris** [comment]
Hi there, could you update this in transifex please? https://www.transifex.com/smileychris/django-countries/

**Comment by laowantong** [comment]
It was already done.

**Comment by SmileyChris** [comment]
Thanks! I'll pull it in soon and roll a release.

**Comment by SmileyChris** [comment]
@laowantong Released 3.5.2, thanks again

**Comment by laowantong** [comment]
Thanks a lot !

**Pull request closed without merging**
