### PR TITLE
Closes #91 -- add countries.by_name

### LINKED ISSUE #91: Add ability to query by country name
It would be nice to be able to do this so I don't need to add yet another package to get that functionality. Is there any interest in a pull request with this functionality?

### PR DESCRIPTION
**Pull request by jschneier**

### CODE REVIEW

**Comment by jschneier** [comment]
Corresponding pull request. Not 100% sure what to do about the issue of translation since I'm piggybacking off of ``__iter__``. I'm curious to hear your thoughts on my implementation. I also couldn't figure out how to run the tests locally so I hope this works...

**Comment by jschneier** [comment]
Ah you run ``tox`` locally. I usually let travis take care of that for me. Looks like they are passing for me.

**Comment by jschneier** [comment]
Well, looks like it fails on Django LTS but that's not due to my patch. You are importing ``format_html`` in widgets.py and that doesn't exist in Django 1.4.x

**Comment by SmileyChris** [comment]
Ah yeah thanks, I merged that in without checking from another request... I really should hook up travis...

I'll take a look at this tomorrow -- thanks for your work :)

**Comment by jschneier** [comment]
I've rebased this down to a single commit, let me know what you think!

**Comment by jschneier** [comment]
ping!

**Pull request merged**
