### PR TITLE
Fix tests with djangorestframework >= 3.8.0

### PR DESCRIPTION
**Pull request by bkabrda**

### CODE REVIEW

**Comment by SmileyChris** [comment]
Need to change `tox.ini` to have `drf{37,38}`

**Comment by bkabrda** [comment]
Ugh, I've never really used tox.ini before, so I'm not 100 % sure where to add these... do you mean I should change every occurence of `drf37` in `envlist` lines for `drf{37,38}`?

**Comment by SmileyChris** [comment]
Yep, that's pretty much it. `pip install .[dev]` then run `tox` to test locally 😀

**Comment by bkabrda** [comment]
Done, hopefully it works fine :)

**Pull request merged**
