### PR TITLE
add type hints to country field

### LINKED ISSUE #382: Call to untyped function "CountryField" in typed context
mypy complains about `Call to untyped function "CountryField" in typed context` as it's not typed.

### PR DESCRIPTION
**Pull request by Mng-dev-ai**
Fixes #382

### CODE REVIEW

**Comment by Mng-dev-ai** [comment]
Hey, @SmileyChris any reasons why checks failed?

**Comment by SmileyChris** [comment]
I've fixed the failing test that's unrelated -- just rebase from master. It would be good having a test showing what this is actually fixing, since the test suite is already passing, including a `mypy` run.

**Comment by Mng-dev-ai** [comment]
Done.

**Comment by SmileyChris** [comment]
I'm still somewhat confused of what we're actually "fixing" here.

**Comment by Mng-dev-ai** [comment]
As I described in #382 if you trying to use the Country field in your models mypy will complain about `Call to untyped function "CountryField" in typed context`

**Comment by Mng-dev-ai** [comment]
@SmileyChris any updates?

**Comment by SmileyChris** [comment]
Haven't had a chance to update you. It'd be great if there was a unit test that proved this actually fixing something. Also, I wonder if there are better types that should be used for the params

**Comment by Mng-dev-ai** [comment]
@SmileyChris Simply add `disallow_untyped_calls = true` to your `setup.cfg` configuration and you will see the error I'm talking about.
About the types for `*args` and `**kwargs` I don't think it could be better because it's actually could be many types in our case

**Comment by SmileyChris** [comment]
Thanks, I got carried away and improved a bunch of the typing. :D

**Comment by Mng-dev-ai** [comment]
Cool, Thank you

**Pull request closed without merging**
