### PR TITLE
Sort country list by localized name

### PR DESCRIPTION
**Pull request by inirudebwoy**
Hi,

Very nice package, saved me a lot of time preparing form.
However one thing missing is sorting fields by localized names instead of value.
I have created a form field in my own form instance in order to have values sorted but I feel
this should be done automatically and seamlessly based on used translation.
I was trying to figure out a place where this sorting can be done. LazyChoiceMixin is a place
where this can be done however I feel like it is not the best place to do it. It is a generic class
but on the other hand it is used in handling choices only.
What are your thoughts?

### CODE REVIEW

**Comment by SmileyChris** [comment]
Um, the countries *are* already sorted by localized names...
https://github.com/SmileyChris/django-countries/blob/master/django_countries/__init__.py#L148

**Comment by Proper-Job** [comment]
@inirudebwoy I just had a similar problem.  Turns out I forgot to add django_countries to my list of installed_apps :(

**Comment by inirudebwoy** [comment]
Sure, thanks for replies. 
I am dealing with arabic translation and it was hard for me to verify the sorting myself.
Issue has been reported by one of the users and I have noticed that order of elements in select differs from list sorted by me. Will verify that and get back to you.

**Comment by SmileyChris** [comment]
Also, for better accuracy of sorting you should install
https://pypi.python.org/pypi/pyuca/ which django-countries will
automatically work with.

**Comment by inirudebwoy** [comment]
@SmileyChris  thanks.
I have tried to replicate issue with my native language and came to conclusion that some more sophisticated sorting is needed. Started reading about pyuca, locale and pyicu.

Great to know but would be really useful if you mention pyuca support in README.md.

**Pull request closed without merging**
