### PR TITLE
Enable to override common names

### PR DESCRIPTION
**Pull request by Godod**
This is code enable to override common countries names, because another solution - it's override method in class Countries

### CODE REVIEW

**Comment by SmileyChris** [comment]
What's the use case not covered by just using `COUNTRIES_OVERRIDE` for the names you wish to change?

**Comment by Godod** [comment]
Use case:
1) If I don't want to use COMMON_NAMES. I want to use ISO_3166-1 country names
2) If I want to change some countries name in COMMON_NAMES
3) I use django_countries with django_phonumber_field and I want to change the country and change the user phonenumber country. If I change country to Russia, I have phone country as Kazakhstan and I must change country in phonenumber widget by JS. I using the following code below:

```javascript
$(function() {
    var parse_text = function(text) {
        var pattern = '[a-zA-Z\\s,]+';
        var regex = text.match(pattern);
        if (regex) {
            return regex[0].toString().trim();
        }
        return ''
    };

    var country_select = $('select#id_country');
    var phone_select = $('select#id_phone_0');
    var country_name = parse_text(country_select.find('option:selected').text().trim());
    var phone_name = parse_text(phone_select.find('option:selected').text().trim());

    if (country_name != phone_name) {
        $.each(phone_select.find('option'), function(index, option) {
            var opt = $(option);
            var parse = parse_text(opt.text().trim());
            if(parse == country_name) {
                var text = opt.text().trim();
                var select2_container = $('#select2-id_phone_0-container');
                phone_select.find('option:selected').removeAttr('selected');
                opt.attr('selected', 'selected');
                select2_container.attr('title', text);
                select2_container.text(text);
            }
        });
    }
});```

**Comment by SmileyChris** [comment]
1. It's not documented, but if you want to not use common names at all, you
can use the following setting `COUNTRIES_COMMON_NAMES = []`
2. `COUNTRIES_OVERRIDE` will still override the common names.
3. I can't see why that javascript requires a custom common name, if
anything it is the same issue as point 2.

**Comment by Godod** [comment]
@SmileyChris Thank you. You may close the pull request

**Pull request closed without merging**
