### PR TITLE
Add country template tag

### PR DESCRIPTION
**Pull request by loop0**

### CODE REVIEW

**Comment by SmileyChris** [comment]
Thanks for this, Bruno!

What's your reasoning behind calling the tag library `countries_tags` -- isn't the `_tags` redundant?

**Comment by loop0** [comment]
There's no reasoning about the tag library name, it's a pattern that I observed in other third parties I use (like django-crispy-forms).

**Comment by loop0** [comment]
Do you need anything else to merge this pull request?

**Comment by SmileyChris** [comment]
Added to 3.4 release, thanks for your work @loop0

**Pull request closed without merging**
