### PR TITLE
Renamed zh_CN to zh_Hans

### PR DESCRIPTION
**Pull request by dongcarl**
See: https://docs.djangoproject.com/en/1.9/internals/deprecation/#deprecation-removed-in-1-9

### CODE REVIEW

**Comment by SmileyChris** [comment]
This should be fixed in transifex, then we can pull in the latest translations from there. Do you want to see if you can assist with that, Carl?

**Comment by SmileyChris** [comment]
Actually, from reading up on transifex features I see this:

> This feature has been dropped, since there were some issues with it. You can achieve the same effect by cloning the language and copying all members of the previous language to the new one.

I'll have a go at that now...

**Comment by SmileyChris** [comment]
Also on a semi-related note, someone requested a `zh_CN.GB2312` translation. Could you explain to me @dongcarl how this differs from the primary one? Does it makes sense to have this as a separate translation too?

**Comment by SmileyChris** [comment]
Done.

**Comment by dongcarl** [comment]
Awesome! :tada:

**Comment by SmileyChris** [comment]
transifex uses "zh-Hans" rather than an underscore which is interesting. I've gone with that -- if you want to test it out, I'd be grateful.

**Comment by dongcarl** [comment]
@SmileyChris both zh-Hans and zh-CN are updated for #134... Not sure why transifex does that... Would that mean the folder under locale would be named zh-Hans? For the `zh_CN.GB2312` translation... I believe it is an old character encoding format for Chinese text... Apparently it's still quite popular in Chinese sites,,,

**Comment by SmileyChris** [comment]
Thanks for the translation updates and clarification of the other character encoding format.

Yes, I renamed the locale directory to `zh-Hans` which let it be uploaded to transifex. I'm not sure if that actually means it works in Django though! Like I said, if you can figure out how to test it then that'd be appreciated.

**Pull request merged**
